#!/bin/sh

# Fix ownership on each invocation. Disabled, let the user handle it
#sudo chown -R `id -u`.`id -g` \
#    ${RHODECODE_INSTALL_DIR}/ \
#    ${RHODECODE_REPO_DIR}

# Reset if needed (e.g. when bind-mounting)
#  Note reset_image won't do anything if files are present
/reset_image >/dev/null 2>&1

exec supervisord -c ${RHODECODE_INSTALL_DIR}/supervisor/supervisord.ini
