version: '2.4'

args:


services:
  rhodecode:
    container_name: rhodecode
    image: outlyernet/rhodecode-ce
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
      - 3690
    ports:
      - "8080:80"
      # No point in publishing svnserve's port since svn disabled
      #- "3690:3690"
    volumes:
      - rhodecode_repos:/home/rhodecode/repo
      - rhodecode_conf:/home/rhodecode/.rccontrol/community-1
      - rhodecode_vcs_conf:/home/rhodecode/.rccontrol/vcsserver-1

# Persist all important data
volumes:
  rhodecode_repos:      # Repositories are stored here
    name: "rhodecode_repos"
  rhodecode_conf:   # RhodeCode's configuration is stored here
    name: "rhodecode_conf"
  rhodecode_vcs_conf:   # RhodeCode's VCS configuration is stored here
    name: "rhodecode_vcs_conf"
