version: '2'

services:
  rhodecode:
    container_name: rhodecode
    image: outlyernet/rhodecode-ce
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
      - 3690
    ports:
      - "8080:8080"
      - "3690:3690"
    volumes:
     - ./volumes/rhodecode/repo:/home/rhodecode/repo
