version: '2.4'

services:
  rhodecode:
    container_name: ${RHODECODE_CONTAINER_NAME:-rhodecode}
    image: outlyernet/rhodecode-ce
    platform: linux # AMD64 RhodeCode by default. IA-32 can be enabled by tweaking the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
      - 3690
    ports:
      - "8080:80"
      # No point in publishing svnserve's port since svn disabled
      #- "3690:3690"
    volumes:
      - rhodecode_repos:/home/rhodecode/repos
      - rhodecode_conf:/home/rhodecode/.rccontrol/community-1
      - rhodecode_vcs_conf:/home/rhodecode/.rccontrol/vcsserver-1
    #tmpfs: # TODO: This doesn't work, /run gets mounted but ends up empty
      #  - /run

# Persist all important data
volumes:
  rhodecode_repos:      # Repositories are stored here
    name: "${RHODECODE_CONTAINER_NAME:-rhodecode}_repos"
  rhodecode_conf:   # RhodeCode's configuration is stored here
    name: "${RHODECODE_CONTAINER_NAME:-rhodecode}_conf"
  rhodecode_vcs_conf:   # RhodeCode's VCS configuration is stored here
    name: "${RHODECODE_CONTAINER_NAME:-rhodecode}_vcs_conf"
