version: '2'


services:

  db:
    container_name: rhodecode_db
    image: mariadb
    environment:
      MYSQL_DATABASE: rhodecode
      MYSQL_USER: rhodecode
      MYSQL_PASSWORD: rhodecode
      MYSQL_ROOT_PASSWORD: rhodecode
    volumes:
     - /var/lib/mysql
    volumes:
     - ./volumes/db:/var/lib/mysql

  rhodecode:
    container_name: rhodecode
    #image: darneta/rhodecode-ce-dockerized
    build:
      context: .
      dockerfile: Dockerfile
    links:
     - db:db
    environment:
      RHODECODE_DB: "mysql://rhodecode:rhodecode@db/rhodecode"
    volumes:
     - ./volumes/rhodecode/repo:/home/rhodecode/repo
