version: '2.4'

# This is an override file for the base configuration.
# Use like:
# $ docker-compose -f docker-compose.yaml -f docker-compose.mariadb.yaml up

services:
  db:
    container_name: ${RHODECODE_CONTAINER_NAME:-rhodecode}_db
    image: mariadb
    environment:
      MYSQL_DATABASE: rhodecode
      MYSQL_USER: rhodecode
      MYSQL_PASSWORD: rhodecode
      MYSQL_ROOT_PASSWORD: rhodecode
    volumes:
      - rhodecode_db:/var/lib/mysql
  rhodecode: # When used as an override will use the base configuration and merge this with it
    depends_on:
      - db

volumes:
  rhodecode_db: 
    name: "${RHODECODE_CONTAINER_NAME:-rhodecode}_db"

