version: '2.4'

services:
  rhodecode:
    container_name: ${RHODECODE_CONTAINER_NAME:-rhodecode}
    image: outlyernet/rhodecode-ce:${RHODECODE_CONTAINER_LABEL:-latest}
    platform: linux # AMD64 RhodeCode by default. IA-32 can be enabled by tweaking the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
      - 3690
    ports:
      - "8080:8080"
      # No point in publishing svnserve's port since svn disabled
      #- "3690:3690"
    volumes:
      - rhodecode_repos:/repos
      - rhodecode_data:/rhodecode
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    #tmpfs: # TODO: This doesn't work, /run gets mounted but ends up empty
      #  - /run

# Persist all important data
volumes:
  rhodecode_repos:      # Repositories are stored here
    name: "${RHODECODE_CONTAINER_NAME:-rhodecode}_repos"
  rhodecode_data:       # RhodeCode's configuration is stored here
    name: "${RHODECODE_CONTAINER_NAME:-rhodecode}_data"
