version: '2'

services:
  rhodecode:
    container_name: rhodecode
    image: outlyernet/rhodecode-ce
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
      - 3690
    ports:
      - "8080:80"
      # No point in publishing svnserve's port since svn disabled
      #- "3690:3690"
    volumes:
     - ./volumes/rhodecode/repo:/home/rhodecode/repo
